INSERT INTO USER(USER_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (1, "admin" , "$2a$08$1Dnhpsakdnmaksndlkasndklas22", "admin", 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY(USER_ID, AUTHORITY_NAME) values (1, "ROLE_USER");
INSERT INTO USER_AUTHORITY(USER_ID, AUTHORITY_NAME) values (1, "ROLE_ADMIN");